In [1]:
import numpy as np

x + y = 3

3x - 2y = 4

Result:

x = 2

y = 1

(2, 1)

In [2]:
import numpy as np

In [3]:
a = np.array([
    [1, 1],
    [3, -2]
])

b = np.array([3, 4])

In [4]:
a

array([[ 1,  1],
       [ 3, -2]])

In [5]:
b

array([3, 4])

In [6]:
c = np.linalg.solve(a, b)

In [7]:
c

array([2., 1.])

In [9]:
# Verify
np.allclose(np.dot(a, c), b)

True

Ref:

https://www.cliffsnotes.com/study-guides/algebra/linear-algebra/linear-systems/gaussian-elimination

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

x - 2y + z = 0

2x + y - 3z = 5

4x - 7y + z = -1

In [10]:
a = np.array([
    [1, -2, 1],
    [2, 1, -3],
    [4, -7, 1]
])

b = np.array([0, 5, -1])

In [11]:
c = np.linalg.solve(a, b)

In [12]:
c

array([3., 2., 1.])