In [1]:
import numpy
import numpy as np
import random as rn

Task 1:

In [2]:
values = numpy.zeros(20)
print(values)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Task 2:

In [3]:
values = np.random.randint(2, 10, size=10)
print(values)

[9 4 6 4 7 8 3 5 3 5]


Task 3:
<br>
Generate a 2 x 4 array of ints between 0 and 4, inclusive:

In [4]:
values = np.random.randint(5, size=(2, 4))
print(values)

[[2 3 0 1]
 [4 4 1 2]]


Task 5:

In [5]:
x = np.arange(6)
print(x)
x = x.reshape((2, 3))
print(x)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


Task 6: Numpy array with random NaNs

In [6]:
M = 10
N = 5
c = 15
A = np.random.randn(M,N)

A.ravel()[np.random.choice(A.size, c, replace=False)] = np.nan
print(A)

[[            nan -3.77369428e-03             nan  5.80261109e-01
  -1.16561732e+00]
 [            nan -6.36186739e-01             nan  1.18721455e-02
   4.87987916e-01]
 [ 8.50140012e-01  1.95363191e-03 -8.78700766e-01 -1.04212409e+00
              nan]
 [ 5.97872768e-01  2.24815451e-01  1.49680880e+00 -4.19741317e-01
  -1.48726639e+00]
 [ 3.86028995e-01             nan -1.22647014e+00             nan
  -1.07890884e+00]
 [ 1.99142811e+00             nan -6.10359603e-01 -1.19508636e+00
              nan]
 [ 3.11533029e-01             nan -5.45338268e-01  1.25066100e+00
   1.47876547e-01]
 [            nan             nan -2.22824834e-01 -7.07785328e-01
              nan]
 [-1.37991098e+00  7.90191612e-01 -2.01301013e+00             nan
  -2.70705763e-02]
 [-2.98487726e-01 -8.29476753e-02  1.01452473e+00             nan
   4.83649471e-01]]


Task 7: Numpy Ravel

In [24]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ravel(x))

[1 2 3 4 5 6]


Task 8: Reshape

In [25]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.reshape(6,))

[1 2 3 4 5 6]


Task 8.1:

In [26]:
print(np.__version__)
print(np.show_config())

1.14.3
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3.5\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3.5\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3.5\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl

Task 9: Create a null vector of size 10

In [27]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Task 10: 

In [28]:
x = np.zeros((10,10))
print("%d bytes" % (x.size * x.itemsize))

800 bytes


Task 11: Create a null vector of size 10 but the fifth value which is 1

In [29]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 12:

In [30]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 13:

In [31]:
x = np.arange(50)
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Task 14:

In [32]:
x = np.arange(10,50, 2)
print(x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


Task 15:

In [33]:
list = [1,2,3,4]
arr = np.array(list)
print(arr)

[1 2 3 4]


Task 16:

In [34]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


Task 17: Zero with int types

In [35]:
print(np.zeros((2, 3), dtype=int).reshape(6,))

[0 0 0 0 0 0]


Task 18: Zeros with reshape

In [36]:
print(np.zeros((2, 3), dtype=int).reshape(6,))

[0 0 0 0 0 0]


Task 19: Ones like

In [37]:
x = np.arange(12)
print(x) 
x = x.reshape((3, 4))
print(x)
y = np.ones_like(x, dtype=int, order='C')
print(y)
y = np.ones_like(x, dtype=float, order='C')
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Task 20:

In [38]:
x = np.arange(6).reshape((3, 2))
print(x)
x = np.full_like(x, np.nan, dtype=np.double, order='C')
print(x)

[[0 1]
 [2 3]
 [4 5]]
[[nan nan]
 [nan nan]
 [nan nan]]


Task 21:

In [39]:
x = np.arange(6).reshape((3, 2))
print(x)
x = np.full_like(x, np.nan, dtype=np.int, order='C')
print(x)

[[0 1]
 [2 3]
 [4 5]]
[[-2147483648 -2147483648]
 [-2147483648 -2147483648]
 [-2147483648 -2147483648]]


Task 22:

In [40]:
x = np.arange(2, 10, dtype=int).reshape(4, 2)
print(x)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Task 23:

In [41]:
x = np.linspace(2, 16, 20, endpoint=False, dtype=int)
print(x)

[ 2  2  3  4  4  5  6  6  7  8  9  9 10 11 11 12 13 13 14 15]


Task 24:

In [42]:
x = np.matrix('1 2; 3 4')
print(x)

[[1 2]
 [3 4]]


Task 25: Numpy with ndim

In [43]:
x = np.array([1, 2, 3, 6, 7], ndmin=3)
print(x)

[[[1 2 3 6 7]]]


Task 26: Random numbers

In [44]:
x = np.random.rand(10)
print(x)

[0.94691203 0.35889332 0.88770714 0.36970931 0.41463094 0.30089522
 0.04237346 0.36368481 0.57939977 0.4827206 ]


Task 27:

In [45]:
x = np.random.randint(5, size=10)
print(x)

[4 2 1 4 3 0 1 0 2 2]


Task 28: low, high and reshape

In [46]:
x = np.random.randint(low=2, high=20, size=6).reshape(3, 2)
print(x)

[[ 7 18]
 [ 6 19]
 [12  6]]


Task 29:

In [47]:
x = np.random.randint(20, size=(2, 5))
print(x)

[[11  3  3  3 18]
 [11 11 16 16 18]]


Task 30: Create an NaN Vector with fifth value

In [48]:
x = np.empty((6,))
x.dtype = int
x[2] = 89
print(x)

[         0 2146959360         89 2146959360          0 2146959360
          0 2146959360          0 2146959360          0 2146959360]


Task 31: Change numpty datatype

In [49]:
x = np.random.randint(10, size=3)
print(x)
x.dtype = bool
print(x)

[8 8 5]
[ True False False False  True False False False  True False False False]


Task 32:

Task 33: print the number of array dimension

In [50]:
x = np.arange(12)
print(x)
print(x.ndim)

x = x.reshape(2, 2, 3)
print(x)
print(x.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


Task 34: values from 100, 200

In [51]:
x = np.arange(100, 200)
print(x)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


Task 35: Reverse the array

In [52]:
x = np.arange(10, 20)
print(x)
x = x[::-1]
print(x)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


Task 36:

In [53]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


Task 37: Identity matrix

In [55]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Task 38:

In [56]:
x = np.eye(4)
print(x)    
if(x.shape[0] == x.shape[1]) and np.allclose(x, np.eye(x.shape[0])):
    print('Identity matrix')
else:
    print('Not an Identity matrix')
     
x = x + 1     
print(x)  
if(x.shape[0] == x.shape[1]) and np.allclose(x, np.eye(x.shape[0])):
    print('Identity matrix')
else:
    print('Not an Identity matrix')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Identity matrix
[[2. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]
Not an Identity matrix


Task 39: Check square matrix

In [57]:
x = np.arange(1, 11).reshape(5, 2)
print(x)

print(x.shape[0])
print(x.shape[1])

if(x.shape[0] == x.shape[1]):
    print('Square matrix')
else:
    print('Not a Square matrix')

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
5
2
Not a Square matrix


Task 40: Check two matrices are identical

In [58]:
x = np.eye(3)    
m = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(x)
print(m)
print(np.all(np.equal(x, m)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
True


Task 41: Array with random values

In [59]:
x = np.random.random((2,7,3))
print(x)

[[[0.42555259 0.67028738 0.50076585]
  [0.40604414 0.23197477 0.19390137]
  [0.52930517 0.35880116 0.70321155]
  [0.96158761 0.83168171 0.44519006]
  [0.79056586 0.46395397 0.9490489 ]
  [0.26056003 0.24380305 0.35675246]
  [0.74134903 0.85402066 0.816364  ]]

 [[0.51039331 0.97325091 0.4928662 ]
  [0.96537238 0.5215961  0.91347714]
  [0.7997755  0.78865932 0.8226284 ]
  [0.06990029 0.12044669 0.52892197]
  [0.21032614 0.73170593 0.31952182]
  [0.47629139 0.20321633 0.38830521]
  [0.99838757 0.54062505 0.44263213]]]


Task 42:

In [60]:
x = np.random.random((2,3))
print(x)
xmin, xmax = x.min(), x.max()
print(xmin, xmax, x.mean())

[[0.5320141  0.04933393 0.42985953]
 [0.83027586 0.03705113 0.47982522]]
0.03705113238096602 0.8302758585011929 0.39305996234787793


Task 43: 1 on the border and 0 inside

In [61]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Task 44: 2 on the border and 0 inside

In [62]:
x = np.full((5, 5), 2)
x[1:-1,1:-1] = rn.randint(1, 10)
print(x)

[[2 2 2 2 2]
 [2 3 3 3 2]
 [2 3 3 3 2]
 [2 3 3 3 2]
 [2 2 2 2 2]]


Task 45:

In [63]:
x = np.ones((5,5), dtype=int)
x = np.pad(x, pad_width=1, mode='constant', constant_values=(2, 8))
print(x)

[[2 2 2 2 2 2 8]
 [2 1 1 1 1 1 8]
 [2 1 1 1 1 1 8]
 [2 1 1 1 1 1 8]
 [2 1 1 1 1 1 8]
 [2 1 1 1 1 1 8]
 [2 8 8 8 8 8 8]]


Task 46: numpy padding function

In [64]:
x = np.random.randint(10, size=(4, 5))
print(x)
print(np.pad(x, (1,), 'mean'))

[[9 7 5 6 9]
 [5 8 8 0 6]
 [2 1 6 5 7]
 [2 4 9 4 5]]
[[5 4 5 7 4 7 5]
 [7 9 7 5 6 9 7]
 [5 5 8 8 0 6 5]
 [4 2 1 6 5 7 4]
 [5 2 4 9 4 5 5]
 [5 4 5 7 4 7 5]]


Task 47:

In [65]:
x = np.random.randint(10, size=(4, 5))
print(x)
print(np.pad(x, (1,), 'median'))

[[8 0 0 1 3]
 [4 8 0 0 8]
 [4 9 3 1 5]
 [8 9 3 1 2]]
[[4 6 8 2 1 4 4]
 [1 8 0 0 1 3 1]
 [4 4 8 0 0 8 4]
 [4 4 9 3 1 5 4]
 [3 8 9 3 1 2 3]
 [4 6 8 2 1 4 4]]


Task 48: Custom pad with numpy

In [66]:
x = np.arange(6)
x = x.reshape((2, 3))
print(x)    

def custom_pad(vector, pad_width, iaxis, kwargs):
    vector[:pad_width[0]] = 5
    vector[-pad_width[1]:] = 10
    return vector
    
print(np.pad(x, 1, custom_pad))

[[0 1 2]
 [3 4 5]]
[[ 5  5  5  5 10]
 [ 5  0  1  2 10]
 [ 5  3  4  5 10]
 [ 5 10 10 10 10]]


Task 49:

In [67]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.inf <= np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
False
nan
False


Task 50:

In [68]:
x = np.diag(1+np.arange(4),k=0)
print(x)
x = np.diag(1+np.arange(4),k=2)
print(x)
print(x.shape)
print(np.diag((2, 3, 7, 8), k=-2))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
(6, 6)
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [2 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 8 0 0]]


Task 51: Checker board

In [69]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Task 52:

Task 53: Unravel

In [70]:
x = np.array((6,7,8))
print(np.unravel_index(10, (2, 5, 2)))
#print(x)
print(np.unravel_index(99,(6,7,8)))
print(np.unravel_index(0,(2,2)))

(1, 0, 0)
(1, 5, 3)
(0, 0)


Task 54:

In [71]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Task 55:

In [72]:
x = np.array([0, 1, 2])
print(x)
print(np.tile(x, 10))
x = np.arange(8)
print(np.tile(x, 2))

[0 1 2]
[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
[0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7]


Task 56: Arange multi dimensional

In [73]:
x, y = np.mgrid[5:8:1, 2:8:2]
print(x)
print(y)

[[5 5 5]
 [6 6 6]
 [7 7 7]]
[[2 4 6]
 [2 4 6]
 [2 4 6]]


Task 57: How to normalize a random matrix

In [74]:
x = np.random.randint(2, 10, size=(2, 4))
xmax, xmin = x.max(), x.min()
xnorm = (x - xmin)/(xmax - xmin)
print(x)
print(xnorm)

[[4 9 3 9]
 [2 3 4 9]]
[[0.28571429 1.         0.14285714 1.        ]
 [0.         0.14285714 0.28571429 1.        ]]


Task 58: Custom datatype

In [75]:
kerneldt = np.dtype([('c_int', np.int32), ('c_duble', np.double, 2)])
arr = np.empty((2, 3), dtype=kerneldt)
print(arr)
print(arr.dtype)

[[(0, [4.24399158e-314, 2.12199579e-314])
  (2, [2.12199579e-314, 9.88131292e-324])
  (1, [9.88131292e-324, 4.24399158e-314])]
 [(0, [4.24399158e-314, 2.12199579e-314])
  (2, [2.12199579e-314, 9.88131292e-324])
  (1, [9.88131292e-324, 4.24399158e-314])]]
[('c_int', '<i4'), ('c_duble', '<f8', (2,))]


Task 59: Matrix multiplication

In [76]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)
y = np.ones((5,4)) @ np.ones((4,2))
print(y)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


Task 60: Negation

In [77]:
x = np.arange(11)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


Task 61:

Task 62:

Task 63:

Task 64: common values between two arrays

In [78]:
x1 = np.random.randint(20, 30, 10)
print(x1)
x2 = np.random.randint(20, 30, 10)
print(x2)
print(np.intersect1d(x1,x2))

[29 27 28 25 29 27 26 25 20 23]
[29 25 22 26 26 21 27 20 20 23]
[20 23 25 26 27 29]


Task 65:

In [81]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

today     = np.datetime64('today', 'D')
print(today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2018-08-23
2018-08-24
2018-08-25


Task 65.1:

In [82]:
now = np.datetime64('today', 'h')
print(now)
    
after_one_hour  = np.datetime64('today', 'D') + np.timedelta64(1, 'h')    
print(after_one_hour)

2018-08-24T00
2018-08-24T01


Task 66: Print dates of a month

In [83]:
x = np.arange('2015-02', '2015-03', dtype='datetime64[D]')
print(x)

['2015-02-01' '2015-02-02' '2015-02-03' '2015-02-04' '2015-02-05'
 '2015-02-06' '2015-02-07' '2015-02-08' '2015-02-09' '2015-02-10'
 '2015-02-11' '2015-02-12' '2015-02-13' '2015-02-14' '2015-02-15'
 '2015-02-16' '2015-02-17' '2015-02-18' '2015-02-19' '2015-02-20'
 '2015-02-21' '2015-02-22' '2015-02-23' '2015-02-24' '2015-02-25'
 '2015-02-26' '2015-02-27' '2015-02-28']


Task 67: Matrix values from 10, 14

In [84]:
x = np.zeros((5,5))
x += np.arange(10, 15)
print(x)

[[10. 11. 12. 13. 14.]
 [10. 11. 12. 13. 14.]
 [10. 11. 12. 13. 14.]
 [10. 11. 12. 13. 14.]
 [10. 11. 12. 13. 14.]]


Task 68:

In [85]:
def generate():
    for x in range(10):
        yield x+5
x = np.fromiter(generate(),dtype=int,count=-1)
print(x)

[ 5  6  7  8  9 10 11 12 13 14]


Task 69:

Task 70:

Task 71:

Task 72:

Task 73:

Task 74:

Task 75:

Task 76:

Task 77:

Task 78:

Task 79:

Task 80:

Task 81:

Task 82:

Task :83

Task 84:

Task 85:

Task 86:

Task 87:

Task 88:

Task 89:

Task 90: