In [1]:
import numpy as np

Let's create an object with zeros

In [2]:
zeros = np.zeros(10)

zeros

In [8]:
print(type(zeros))

<class 'numpy.ndarray'>


Now, we can assign the zeros into a variable

In [4]:
x = np.zeros(10)

In [5]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

now, we can fill up 1 from 5 th element onward

In [7]:
x[5:] = 1


In [9]:
print(x)

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]


Assignment:
Print 20 elements with first 5 elements as 1, next 5 elements with 2, next 5 elements with 0, the last 5 elements with 8

In [12]:
x1 = np.linspace(0, 1, 2000)

In [13]:
x1

array([0.00000000e+00, 5.00250125e-04, 1.00050025e-03, ...,
       9.98999500e-01, 9.99499750e-01, 1.00000000e+00])

more linspace can be found here:
<br>
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linspace.html

In [14]:
np.linspace(1, 5, num=5)

array([1., 2., 3., 4., 5.])

In [15]:
np.linspace(1, 5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [17]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [19]:
np.linspace(1, 5, 5, dtype=int, endpoint=False)

array([1, 2, 3, 4, 5])

In [20]:
np.linspace(1, 5, 5, dtype=int, endpoint=False)

array([1, 1, 2, 3, 4])

In [21]:
np.linspace(1, 5, 5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [22]:
x1 = np.linspace(0, 1, 2000)

In [23]:
x1

array([0.00000000e+00, 5.00250125e-04, 1.00050025e-03, ...,
       9.98999500e-01, 9.99499750e-01, 1.00000000e+00])

In [24]:
x1[1000:] = np.linspace(0, 1, 1000)

In [25]:
x1

array([0.00000000e+00, 5.00250125e-04, 1.00050025e-03, ...,
       9.97997998e-01, 9.98998999e-01, 1.00000000e+00])

In [26]:
x1[1500:] = np.linspace(0, 1, 500)

In [27]:
x1

array([0.00000000e+00, 5.00250125e-04, 1.00050025e-03, ...,
       9.95991984e-01, 9.97995992e-01, 1.00000000e+00])

In [28]:
x1.shape

(2000,)

In [29]:
x1 = x1.reshape((1000, 2))

In [30]:
x1.shape

(1000, 2)

In [31]:
x1

array([[0.00000000e+00, 5.00250125e-04],
       [1.00050025e-03, 1.50075038e-03],
       [2.00100050e-03, 2.50125063e-03],
       ...,
       [9.89979960e-01, 9.91983968e-01],
       [9.93987976e-01, 9.95991984e-01],
       [9.97995992e-01, 1.00000000e+00]])